import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* This div component horizontally centers with a top margin */}
        <div className="flex flex-row justify-center mt-32">
          {children}
        </div>
      </body>
    </html>
  );
}
